
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t hello-world-app .
        docker tag hello-world-app:latest <your-dockerhub-username>/hello-world-app:latest
        docker push <your-dockerhub-username>/hello-world-app:latest

    - name: Set up kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
      env:
        KUBECONFIG: ~/.kube/config

    - name: Kubernetes Deployment
      run: |
        kubectl apply -f deployment.yaml

