
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: |
        echo londonlon | docker login -u alakuma --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t hello-world-app .
        docker tag hello-world-app:latest alakuma/hello-world-app:latest
        docker push alakuma/hello-world-app:latest

    - name: Set up kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
      env:
        KUBECONFIG: ~/.kube/config

    #- name: Test Kubernetes connection
    #  run: |
    #    kubectl cluster-info
       
    - name: Kubernetes Deployment
      run: |
        kubectl apply -f deployment.yaml